#!/bin/bash

INSTALLDIR=/usr/local/bin/kernels

./build ellesmere 64
./build ellesmere 128
./build ellesmere 192
./build ellesmere 256 
./build baffin 64
./build baffin 128
./build baffin 192
./build baffin 256 

sudo cp bin/* $INSTALLDIR
